CREATE DATABASE [Lottery]
 CONTAINMENT = NONE
 ON PRIMARY 
( 
  NAME = N'lottery_data01', 
  FILENAME = N'D:\MSSQLServer\MSSQL\Data\lottery_data01.mdf' , 
  SIZE = 1024000KB , 
  FILEGROWTH = 131072KB ),
( NAME = N'lottery_data02', 
  FILENAME = N'D:\MSSQLServer\MSSQL\Data\lottery_data02.ndf' , 
  SIZE = 1024000KB , 
  FILEGROWTH = 131072KB )
  LOG ON 
( NAME = N'lottery_log', 
  FILENAME = N'D:\MSSQLServer\MSSQL\Log\lottery_log.ldf' , 
  SIZE = 512000KB , 
  FILEGROWTH = 65536KB );
GO

ALTER DATABASE [Lottery] SET COMPATIBILITY_LEVEL = 150;
ALTER DATABASE [Lottery] SET ANSI_NULL_DEFAULT OFF;
ALTER DATABASE [Lottery] SET ANSI_NULLS OFF; 
ALTER DATABASE [Lottery] SET ANSI_PADDING OFF; 
ALTER DATABASE [Lottery] SET ANSI_WARNINGS OFF; 
ALTER DATABASE [Lottery] SET ARITHABORT OFF; 
ALTER DATABASE [Lottery] SET AUTO_CLOSE OFF; 
ALTER DATABASE [Lottery] SET AUTO_SHRINK OFF; 
ALTER DATABASE [Lottery] SET AUTO_CREATE_STATISTICS ON(INCREMENTAL = OFF);
ALTER DATABASE [Lottery] SET AUTO_UPDATE_STATISTICS ON;
ALTER DATABASE [Lottery] SET CURSOR_CLOSE_ON_COMMIT OFF; 
ALTER DATABASE [Lottery] SET CURSOR_DEFAULT  GLOBAL; 
ALTER DATABASE [Lottery] SET CONCAT_NULL_YIELDS_NULL OFF; 
ALTER DATABASE [Lottery] SET NUMERIC_ROUNDABORT OFF; 
ALTER DATABASE [Lottery] SET QUOTED_IDENTIFIER OFF; 
ALTER DATABASE [Lottery] SET RECURSIVE_TRIGGERS OFF; 
ALTER DATABASE [Lottery] SET  DISABLE_BROKER; 
ALTER DATABASE [Lottery] SET AUTO_UPDATE_STATISTICS_ASYNC OFF; 
ALTER DATABASE [Lottery] SET DATE_CORRELATION_OPTIMIZATION OFF; 
ALTER DATABASE [Lottery] SET PARAMETERIZATION SIMPLE; 
ALTER DATABASE [Lottery] SET READ_COMMITTED_SNAPSHOT OFF;
ALTER DATABASE [Lottery] SET  READ_WRITE; 
ALTER DATABASE [Lottery] SET RECOVERY SIMPLE; 
ALTER DATABASE [Lottery] SET  MULTI_USER; 
ALTER DATABASE [Lottery] SET PAGE_VERIFY CHECKSUM;  
ALTER DATABASE [Lottery] SET TARGET_RECOVERY_TIME = 60 SECONDS; 
ALTER DATABASE [Lottery] SET DELAYED_DURABILITY = DISABLED;
GO

USE [Lottery]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = Off;
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = Primary;
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = On;
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = Primary;
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = Off;
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = Primary;

USE [Lottery]
GO

IF NOT EXISTS (SELECT name FROM sys.filegroups WHERE is_default=1 AND name = N'PRIMARY') 
  ALTER DATABASE [Lottery] MODIFY FILEGROUP [PRIMARY] DEFAULT;
GO
